### ISSUE TITLE
About the dataset

### ISSUE THREAD

**Issue by fdujay** [HealthML/self-supervised-3d-tasks#1]
Thanks for your code! I'm quite interested in your work, but there are some problems for me to realize your algorithm:
 - `conda env create -f env_all_platforms.yml` is not a good choice, because it will remind me that there're some conflicts, so I have to install the required manully.
 - the right command is `python train.py self_supervised_3d_tasks/configs/train/{algorithm}_{dimension}.json` not `python train.py configs/train/{algorithm}_{dimension}.json`
- I have to comment some codes  in free_gpu_check.py:
```
    if len(gpu_df) < amount:
        raise ValueError("The requested amount of GPUs is not existing.")
    for i in range(amount):
        max_gpu = gpu_df.index[0]
       # if gpu_df.loc[max_gpu]["memory.used"] != 0:
           # error = "The requested amount of GPUs are not available currently."
           # if use_gpu:
               # error += " Try removing the 'use_gpu' flag."

           # raise ValueError(error)
        output.append(max_gpu)
        gpu_df.drop(max_gpu, inplace=True)
```

 - When I run the command above, error comes out:

> FileNotFoundError: [Errno 2] No such file or directory: '/home/davis/workspace/self-supervised-transfer-learning/exemplar_pancreas3d'

So I wonder if you can provide more information about the data preparation? It's quite frustrated to get errors when realizing your awesome algorithm, thanks!

**Comment by wangn123** [comment]
I have the same problem. have you solved it?

**Comment by aihamtaleb** [comment]
Dear @fdujay and @wangn123 thanks for your questions.
With regards to the missing files, I will update the config files now, please make sure to update them yourself. As the paths for the datasets and the model checkpoints will certainly be different in your machines.

**Comment by wangn123** [comment]
Thanks for your reply. When training the model, I didn't see the file in configs for training 2D brats. if I want to train 2D brats, do I just need to change the "data_dir"  to brats,  could you please tell me the input size of 2D brats and 3D brats ?

**Comment by aihamtaleb** [comment]
Yes, indeed. Just change the data_dir to where your dataset is. Please read our documentation for the config flags in README.MD.
The input size of 2D and 3D brats is something you choose, you can resize the images to any resolution you wish.
I will close this issue since it seems to be resolved.
