### ISSUE TITLE
train the baseline model without any pre-train weights

### ISSUE THREAD

**Issue by szhang963** [HealthML/self-supervised-3d-tasks#12]
Hi,
I do not find the code for training the baseline model without any pre-train weights.
I think the code ```finetune.py``` can be modified to satisfy the need, but  I don't study the tensorflow2 thoroughly. Could you give me some suggestions about the code modification?
Thanks in advance.

**Comment by aihamtaleb** [comment]
Hi,
I kindly refer you to the readme documentation: https://github.com/HealthML/self-supervised-3d-tasks/blob/master/README.md 
there is a flag in the finetuning config json file that is called load_weights, please try to set it to false.
Best,

**Comment by szhang963** [comment]
Thanks, I will read the message in detail.
