### ISSUE TITLE
How to load the Brats data after being saved as tfrecord format?

### ISSUE THREAD

**Issue by RooGeerr** [HealthML/self-supervised-3d-tasks#13]
Hi, Thank you for your contribution to the work!
I encountered a problem when i loaded the Brats data that be saved as tfrecord format.
I don't konw how to convert these format to numpy format in 21 line in numpy_3d_loader.py
The error I encountered is " OSError: Failed to interpret file '../3D_label.tfrecord-00002-of-00011' as a pickle"
I hope you can repy as soon as posible!
Best!

**Comment by aihamtaleb** [comment]
Hi,
I think the numpy3d loader doesn't serve your purpose in this case. You'd need probably to create another loader script that handles tf-records. Maybe this blog will be useful: https://androidkt.com/feed-tfrecord-to-keras/
Feel free to create a pull request for your loader if you wish to contribute it.
