### ISSUE TITLE
Pre-training model where to insert path of saved model

### ISSUE THREAD

**Issue by lokeycookie** [HealthML/self-supervised-3d-tasks#19]
Hello, I just come across this repo and wanted to try some pre-training on a Brats dataset.

For pre-training, where do I specify the path to where I want the pre-trained model/weights to be saved in? I can't find this path for saving models parameter in the config files.

**Comment by aihamtaleb** [comment]
Hi, thanks for trying out the repo.
That path is created automatically when you start the training. You can find the line here: https://github.com/HealthML/self-supervised-3d-tasks/blob/9f21099867f3ac10fe232bd60899483079fd7c91/self_supervised_3d_tasks/train.py#L51

You need to pass the correct `base_workspace` as a parameter to `train_model`. Then you will be able to set the path prefix.

**Comment by lokeycookie** [comment]
Hello, thank you! One more question, let's say I have run the pre-training and the finetuning files. After the finetuning, where will the model (eg 3d-unet) be saved at? Do we need to specify the path to where this final model is saved at?
