### ISSUE TITLE
Fine-tuning model: where is the model saved at

### ISSUE THREAD

**Issue by lokeycookie** [HealthML/self-supervised-3d-tasks#20]
Hi, I was reading the research paper and saw that 3D-Unet is eventually trained and evaluated on different sizes of labelled data. After running the pre-training file and fine-tuning file in this repo, where will the model (eg 3D-unet) be saved at? Do we need to specify the path to where this fine-tuned model is saved?

**Comment by aihamtaleb** [comment]
Hi, 
the checkpoint files are saved in the working_dir: https://github.com/HealthML/self-supervised-3d-tasks/blob/9f21099867f3ac10fe232bd60899483079fd7c91/self_supervised_3d_tasks/train.py#L51 

this is an argument you can set easily for the train function

**Comment by aihamtaleb** [comment]
Please notify us if you have further questions. Closing this for now.
