### ISSUE TITLE
Train-test split of Pancreas dataset

### ISSUE THREAD

**Issue by mishgon** [HealthML/self-supervised-3d-tasks#26]
Dear @aihamtaleb,

I am working on a paper and would like to faithfully compare our method with your results. In your paper you wrote 
```
The Pancreas dataset contains annotated CT scans for 420 cases.
...
We should note that we evaluate this task on a held-out labeled subset of the Pancreas dataset that was not used for pretraining nor fine-tuning.
```
However, I can't find any other information about how exactly you selected images for the held-out test set?

My first guess was that you used the same train-test split as in http://medicaldecathlon.com/. But then I realized, that there are no publicly available annotations for the test set.

So, could you please clarify, e.g. share a list of identifiers (like `pancreas_134`, `pancreas_167`, ...) of images from the held-out test set that you used in your experiments?

Sincerely,
Mikhail Goncharov,
PhD Student at Skoltech

**Comment by aihamtaleb** [comment]
Dear @migonch 

The dataset split is this parameter 
"val_split": 0.05,

in the config file.

Cheers,
