### ISSUE TITLE
About UK Biobank dataset

### ISSUE THREAD

**Issue by Scipio1996** [HealthML/self-supervised-3d-tasks#3]
Hello, you said pre-trained on UK Biobank, which contains roughly 22k 3D scans. However, I can only find around 1K brain data. Can you share your download links? Thank you very much!

**Comment by aihamtaleb** [comment]
Hi, thanks for your inquiry.

you're kindly referred to the UKB documentation here: http://biobank.ndph.ox.ac.uk/showcase/exinfo.cgi?src=accessing_data_guide#download 
for information on UKB specific scripts
Beware that the downloading process is split into batches, and the number of patients per batch should be limited to 1000 patient ids. The download script we implemented for this purpose can be found here: https://gitlab.com/statistical-genomics/ukbb_utils
