### ISSUE TITLE
About the kaggle retina dataset preparation

### ISSUE THREAD

**Issue by numancelik34** [HealthML/self-supervised-3d-tasks#4]
Hi there,

Thanks for sharing this repo as it seems very interesting to medical imaging domain. However, it also seems that this repo lacks of explanation for dataset and data preparation tasks. For classification tasks, where is csv file mentioned in the code? 
How can we access the 2D kaggle retina or pancreas dataset? That would be useful for us to share the links as well to properly run this repo? 

Thanks

**Comment by aihamtaleb** [comment]
Hi, thanks for your inquiry.

We just added a sample csv file here: https://github.com/HealthML/self-supervised-3d-tasks/blob/master/self_supervised_3d_tasks/data/example_labels_retina.csv 
We will update the project Readme to reflect this update.

As for the dataset itself, it can be obtained from here: https://www.kaggle.com/c/aptos2019-blindness-detection 

Thanks, Aiham

**Comment by aihamtaleb** [comment]
Additional information about other datasets can be found in our paper: https://arxiv.org/abs/2006.03829
