### ISSUE TITLE
Repo not found

### ISSUE THREAD

**Issue by ramchandracheke** [HealthML/self-supervised-3d-tasks#5]
Hi,

Thanks for this paper and code. However, when I tried to follow the instructions I got follow error message. Can you please guide me.

Cloning into 'self-supervised-3d-tasks'...
remote: The project you were looking for could not be found.
fatal: repository 'https://gitlab.com/statistical-genomics/self-supervised-3d-tasks.git/' not found

Thanks

**Comment by aihamtaleb** [comment]
Hi,
Thank you for your interest in using our repo. Apologies for the incorrect statement in the Readme file, we have corrected it now.
Please use 
``git clone https://github.com/HealthML/self-supervised-3d-tasks.git``

**Comment by ramchandracheke** [comment]
Thanks a million!
