### ISSUE TITLE
Can we run this code on Multigpu Setting?

### ISSUE THREAD

**Issue by ramchandracheke** [HealthML/self-supervised-3d-tasks#8]
Hi,
I am running this code on single GPU. However, it is utilizing all memory. Can we run this on multiple gpu?
Thanks,

**Comment by aihamtaleb** [comment]
Hi,
Our current codebase doesn't support such a request, unfortunately. However, extending this in your clone should be straightforward, according to the following info:
https://datascience.stackexchange.com/a/25737
 
Please check it out, and give it a try. If this works you're welcome to contribute a running script to our repo with a Pull Request.

Cheers

**Comment by ramchandracheke** [comment]
Thanks @aihamtaleb 

Sure I will try and will update you.

Thanks,
